const DESTINATIONS_MAX = 3;
const DESTINATIONS_MID = 2;
const MAX_POINTS = 5;

const Mode = {
  DEFAULT: 'DEFAULT',
  EDITING: 'EDITING',
};

export {DESTINATIONS_MAX, DESTINATIONS_MID, MAX_POINTS, Mode};
